# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Java Application
      run:  java -jar target/bing-wallpaper-jar-with-dependencies.jar
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: update resources
        title: update resources
        body: update resources
        branch: ${{ github.run_id }}
        base: pic

    - name: Enable Pull Request Automerge
      run: gh pr merge --merge --auto "${PULL_REQUEST_NUMBER}"
      env:
        GH_TOKEN: ${{ secrets.PAT }}
